[[redirects]]
  from = "/api/hubspot"
  to = "/.netlify/functions/hubspot"
  status = 200

[[redirects]]
  from = "/api/lineage"
  to = "/.netlify/functions/lineage"
  status = 200

[[redirects]]
  from = "/api/ordinal"
  to = "/.netlify/functions/ordinal"
  status = 200

[[redirects]]
  from = "/hs-api/*"
  to = "https://api.hubapi.com/:splat"
  status = 200
  force = true
